import { Injectable, signal, computed } from '@angular/core';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private products = signal<Product[]>([
    {
      id: 1,
      name: 'Hamburguesa Clásica',
      description: 'Carne de res, lechuga, tomate, queso.',
      longDescription: 'Nuestra hamburguesa clásica con 150g de carne de res jugosa, queso cheddar derretido, lechuga fresca, rodajas de tomate y nuestra salsa especial de la casa, todo en un pan de brioche tostado.',
      price: 25000,
      imageUrl: 'https://picsum.photos/seed/burger1/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 2,
      name: 'Hamburguesa Doble Bacon',
      description: 'Doble carne, doble queso, tocineta.',
      longDescription: 'Para los más hambrientos: doble porción de 150g de carne de res, doble queso cheddar, tocineta crujiente, cebolla caramelizada y salsa BBQ en pan de brioche.',
      price: 35000,
      imageUrl: 'https://picsum.photos/seed/burger2/400/300',
      category: 'Hamburguesas',
    },
     {
      id: 9,
      name: 'Hamburguesa Pollo Crispy',
      description: 'Pechuga de pollo apanada, lechuga, mayonesa.',
      longDescription: 'Deliciosa pechuga de pollo crujiente y apanada, acompañada de lechuga fresca y una suave mayonesa de la casa en pan de sésamo.',
      price: 28000,
      imageUrl: 'https://picsum.photos/seed/burger3/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 15,
      name: 'Hamburguesa BBQ',
      description: 'Carne, aros de cebolla, queso, salsa BBQ.',
      longDescription: 'Una explosión de sabor con 150g de carne de res, aros de cebolla crujientes, queso americano derretido y nuestra salsa BBQ ahumada especial, todo en pan brioche.',
      price: 32000,
      imageUrl: 'https://picsum.photos/seed/burger4/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 16,
      name: 'Hamburguesa Vegana',
      description: 'Torta de lentejas, aguacate, rúgula.',
      longDescription: 'Una opción deliciosa y saludable. Torta casera a base de lentejas y champiñones, con aguacate fresco, rúgula y mayonesa vegana en un pan artesanal.',
      price: 29000,
      imageUrl: 'https://picsum.photos/seed/burger5/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 3,
      name: 'Pizza Margherita',
      description: 'Salsa de tomate, mozzarella, albahaca.',
      longDescription: 'La clásica pizza italiana con salsa de tomate San Marzano, mozzarella fresca de búfala y hojas de albahaca fresca sobre una masa fina y crujiente.',
      price: 30000,
      imageUrl: 'https://picsum.photos/seed/pizza1/400/300',
      category: 'Pizzas',
    },
    {
      id: 4,
      name: 'Pizza Pepperoni',
      description: 'Pepperoni picante y mucho queso.',
      longDescription: 'Una favorita de todos los tiempos. Cubierta generosamente con pepperoni picante y una mezcla de quesos mozzarella y provolone sobre nuestra salsa de tomate casera.',
      price: 32000,
      imageUrl: 'https://picsum.photos/seed/pizza2/400/300',
      category: 'Pizzas',
    },
     {
      id: 10,
      name: 'Pizza Hawaiana',
      description: 'Jamón, piña y queso mozzarella.',
      longDescription: 'La controversial pero deliciosa pizza hawaiana con jugosos trozos de piña, jamón ahumado y queso mozzarella derretido.',
      price: 33000,
      imageUrl: 'https://picsum.photos/seed/pizza3/400/300',
      category: 'Pizzas',
    },
    {
      id: 17,
      name: 'Pizza de Carnes',
      description: 'Pepperoni, salami, jamón, salchicha.',
      longDescription: 'Para los amantes de la carne: una base de salsa de tomate cubierta con pepperoni, salami, jamón y trozos de salchicha italiana, con extra queso mozzarella.',
      price: 38000,
      imageUrl: 'https://picsum.photos/seed/pizza4/400/300',
      category: 'Pizzas',
    },
    {
      id: 18,
      name: 'Pizza Vegetariana',
      description: 'Pimientos, champiñones, aceitunas, cebolla.',
      longDescription: 'Una colorida y sabrosa mezcla de vegetales frescos: pimientos verdes, champiñones, aceitunas negras y cebolla roja sobre nuestra base de pizza clásica.',
      price: 31000,
      imageUrl: 'https://picsum.photos/seed/pizza5/400/300',
      category: 'Pizzas',
    },
    {
      id: 11,
      name: 'Wrap de Pollo César',
      description: 'Pollo a la plancha, lechuga, parmesano, aderezo.',
      longDescription: 'Tiernos trozos de pollo a la plancha, lechuga romana fresca, queso parmesano y aderezo césar, todo envuelto en una tortilla de harina suave.',
      price: 22000,
      imageUrl: 'https://picsum.photos/seed/wrap1/400/300',
      category: 'Wraps',
    },
    {
      id: 12,
      name: 'Wrap Vegetariano',
      description: 'Falafel, hummus, vegetales frescos.',
      longDescription: 'Un wrap saludable y delicioso lleno de falafel crujiente, hummus cremoso, lechuga, tomate, pepino y pimientos frescos.',
      price: 20000,
      imageUrl: 'https://picsum.photos/seed/wrap2/400/300',
      category: 'Wraps',
    },
    {
      id: 19,
      name: 'Wrap de Carne Asada',
      description: 'Carne asada, pimientos, cebolla, queso.',
      longDescription: 'Jugosas tiras de carne asada a la parrilla, con pimientos y cebollas salteadas y queso derretido, envuelto en una tortilla de trigo caliente.',
      price: 24000,
      imageUrl: 'https://picsum.photos/seed/wrap3/400/300',
      category: 'Wraps',
    },
    {
      id: 5,
      name: 'Papas a la Francesa',
      description: 'Porción grande de papas crujientes.',
      longDescription: 'Papas fritas doradas y crujientes, sazonadas a la perfección con sal marina. El acompañamiento ideal para cualquier plato.',
      price: 8000,
      imageUrl: 'https://picsum.photos/seed/fries/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 6,
      name: 'Aros de Cebolla',
      description: 'Aros de cebolla apanados con salsa BBQ.',
      longDescription: 'Crujientes aros de cebolla apanados, servidos con nuestra salsa BBQ casera para un toque ahumado y dulce.',
      price: 10000,
      imageUrl: 'https://picsum.photos/seed/onions/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 20,
      name: 'Palitos de Mozzarella',
      description: 'Dedos de queso apanados con salsa marinara.',
      longDescription: 'Crujientes por fuera y elásticos por dentro. Seis palitos de queso mozzarella perfectamente dorados, servidos con una rica salsa marinara para dipear.',
      price: 13000,
      imageUrl: 'https://picsum.photos/seed/mozzarella/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 13,
      name: 'Malteada de Chocolate',
      description: 'Cremosa y chocolatosa.',
      longDescription: 'Una malteada clásica y cremosa hecha con helado de chocolate premium y leche entera, cubierta con crema batida y sirope de chocolate.',
      price: 12000,
      imageUrl: 'https://picsum.photos/seed/shake1/400/300',
      category: 'Postres',
    },
    {
      id: 14,
      name: 'Brownie con Helado',
      description: 'Brownie caliente con helado de vainilla.',
      longDescription: 'Un brownie de chocolate tibio y fudgy, servido con una bola de helado de vainilla cremoso y un chorrito de salsa de caramelo.',
      price: 15000,
      imageUrl: 'https://picsum.photos/seed/brownie/400/300',
      category: 'Postres',
    },
     {
      id: 21,
      name: 'Cheesecake de Fresa',
      description: 'Cremoso cheesecake con salsa de fresa.',
      longDescription: 'Una rebanada de nuestro cremoso cheesecake estilo Nueva York, cubierto con una dulce y vibrante salsa de fresas frescas.',
      price: 16000,
      imageUrl: 'https://picsum.photos/seed/cheesecake/400/300',
      category: 'Postres',
    },
    {
      id: 7,
      name: 'Gaseosa',
      description: 'Coca-Cola, Sprite, etc.',
      longDescription: 'Refresca tu comida con tu elección de gaseosa: Coca-Cola, Sprite, o Fanta. Servida bien fría.',
      price: 5000,
      imageUrl: 'https://picsum.photos/seed/soda/400/300',
      category: 'Bebidas',
    },
    {
      id: 8,
      name: 'Jugo Natural',
      description: 'Jugo de mora, lulo o mango.',
      longDescription: 'Hecho con fruta fresca. Elige entre mora, lulo o mango para un refresco natural y delicioso.',
      price: 7000,
      imageUrl: 'https://picsum.photos/seed/juice/400/300',
      category: 'Bebidas',
    },
    {
      id: 22,
      name: 'Limonada de Coco',
      description: 'Refrescante y cremosa limonada.',
      longDescription: 'La bebida perfecta para un día caluroso. Una mezcla refrescante de jugo de limón fresco y crema de coco, servida bien fría.',
      price: 9000,
      imageUrl: 'https://picsum.photos/seed/lemonade/400/300',
      category: 'Bebidas',
    },
    {
      id: 23,
      name: 'Agua Embotellada',
      description: 'Agua pura de manantial sin gas.',
      longDescription: 'Mantente hidratado con una botella de agua pura y refrescante.',
      price: 4000,
      imageUrl: 'https://picsum.photos/seed/water/400/300',
      category: 'Bebidas',
    },
    {
      id: 24,
      name: 'Hamburguesa Mexicana',
      description: 'Guacamole, jalapeños, queso monterrey.',
      longDescription: 'Siente el sabor de México con 150g de carne de res, guacamole fresco, jalapeños picantes, queso monterrey jack y un toque de cilantro en pan artesanal.',
      price: 33000,
      imageUrl: 'https://picsum.photos/seed/burger6/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 25,
      name: 'Hamburguesa de Champiñones',
      description: 'Champiñones salteados y queso suizo.',
      longDescription: 'Una combinación sofisticada: 150g de carne de res, champiñones salteados en ajo, queso suizo derretido y mayonesa de trufa en pan de brioche.',
      price: 34000,
      imageUrl: 'https://picsum.photos/seed/burger7/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 26,
      name: 'Mini Hamburguesas (Sliders)',
      description: 'Trío de nuestras mini hamburguesas.',
      longDescription: 'Perfectas para compartir o probar un poco de todo. Tres mini hamburguesas de res con queso cheddar, pepinillos y nuestra salsa especial.',
      price: 36000,
      imageUrl: 'https://picsum.photos/seed/burger8/400/300',
      category: 'Hamburguesas',
    },
    {
      id: 27,
      name: 'Pizza Cuatro Quesos',
      description: 'Mozzarella, provolone, parmesano, gorgonzola.',
      longDescription: 'El paraíso para los amantes del queso. Una deliciosa mezcla de mozzarella, provolone, parmesano y gorgonzola sobre una base de salsa blanca.',
      price: 37000,
      imageUrl: 'https://picsum.photos/seed/pizza6/400/300',
      category: 'Pizzas',
    },
    {
      id: 28,
      name: 'Pizza BBQ Chicken',
      description: 'Pollo BBQ, cebolla roja, cilantro.',
      longDescription: 'Una pizza con un toque ahumado. Tiernos trozos de pollo bañados en salsa BBQ, cebolla roja en rodajas y cilantro fresco.',
      price: 36000,
      imageUrl: 'https://picsum.photos/seed/pizza7/400/300',
      category: 'Pizzas',
    },
    {
      id: 29,
      name: 'Pizza Rústica',
      description: 'Prosciutto, rúgula, lascas de parmesano.',
      longDescription: 'Una pizza elegante con sabores italianos auténticos. Finas lonjas de prosciutto, rúgula fresca y lascas de queso parmesano sobre una base de tomate.',
      price: 39000,
      imageUrl: 'https://picsum.photos/seed/pizza8/400/300',
      category: 'Pizzas',
    },
    {
      id: 30,
      name: 'Wrap de Pavo y Aguacate',
      description: 'Pechuga de pavo, aguacate, espinaca.',
      longDescription: 'Una opción ligera y nutritiva. Pechuga de pavo en finas lonjas, aguacate cremoso, espinaca fresca y un toque de aderezo ranch en una tortilla integral.',
      price: 23000,
      imageUrl: 'https://picsum.photos/seed/wrap4/400/300',
      category: 'Wraps',
    },
    {
      id: 31,
      name: 'Wrap Thai de Pollo Picante',
      description: 'Pollo picante, salsa de maní, vegetales.',
      longDescription: 'Un viaje de sabores a Tailandia. Pollo salteado en una salsa de maní picante, con zanahorias y repollo crujiente, envuelto en una tortilla de harina.',
      price: 25000,
      imageUrl: 'https://picsum.photos/seed/wrap5/400/300',
      category: 'Wraps',
    },
    {
      id: 32,
      name: 'Ensalada de la Casa',
      description: 'Lechugas, tomate, pepino, vinagreta.',
      longDescription: 'Una ensalada fresca para acompañar tu plato. Mezcla de lechugas, tomates cherry, rodajas de pepino y crutones, con nuestra vinagreta de la casa.',
      price: 11000,
      imageUrl: 'https://picsum.photos/seed/salad1/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 33,
      name: 'Papas Cargadas',
      description: 'Papas fritas con queso, tocineta y cebollín.',
      longDescription: 'Nuestras papas a la francesa llevadas al siguiente nivel, cubiertas con abundante queso cheddar derretido, trocitos de tocineta crujiente y cebollín fresco.',
      price: 15000,
      imageUrl: 'https://picsum.photos/seed/loadedfries/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 34,
      name: 'Aros de Calamar',
      description: 'Calamares apanados con alioli de limón.',
      longDescription: 'Tiernos aros de calamar con un apanado crujiente, servidos con un cremoso alioli de limón para una combinación perfecta.',
      price: 18000,
      imageUrl: 'https://picsum.photos/seed/calamari/400/300',
      category: 'Acompañamientos',
    },
    {
      id: 35,
      name: 'Tacos al Pastor',
      description: 'Cerdo marinado, piña, cebolla, cilantro.',
      longDescription: 'El clásico de la comida callejera mexicana. Carne de cerdo marinada en achiote, asada lentamente y servida con piña, cebolla y cilantro en tortillas de maíz.',
      price: 28000,
      imageUrl: 'https://picsum.photos/seed/taco1/400/300',
      category: 'Tacos',
    },
    {
      id: 36,
      name: 'Tacos de Carnitas',
      description: 'Cerdo desmechado, cebolla, cilantro.',
      longDescription: 'Tiernas y jugosas carnitas de cerdo cocinadas a fuego lento, servidas en tortillas de maíz con cebolla, cilantro y un toque de salsa verde.',
      price: 27000,
      imageUrl: 'https://picsum.photos/seed/taco2/400/300',
      category: 'Tacos',
    },
    {
      id: 37,
      name: 'Tacos de Pescado',
      description: 'Pescado apanado, repollo, salsa chipotle.',
      longDescription: 'Estilo Baja California. Filetes de pescado con un apanado ligero, sobre una cama de repollo crujiente y aderezados con nuestra cremosa salsa de chipotle.',
      price: 29000,
      imageUrl: 'https://picsum.photos/seed/taco3/400/300',
      category: 'Tacos',
    },
    {
      id: 38,
      name: 'Torta de Chocolate',
      description: 'Rebanada de torta de chocolate húmeda.',
      longDescription: 'Para los amantes del chocolate, una rebanada generosa de nuestra torta de chocolate con múltiples capas y una rica cobertura de fudge.',
      price: 14000,
      imageUrl: 'https://picsum.photos/seed/cake1/400/300',
      category: 'Postres',
    },
    {
      id: 39,
      name: 'Helado Artesanal',
      description: 'Dos bolas de helado (vainilla/chocolate/fresa).',
      longDescription: 'Refrescante y cremoso. Elige dos bolas de nuestros sabores de helado artesanal: vainilla de Madagascar, chocolate belga o fresa natural.',
      price: 10000,
      imageUrl: 'https://picsum.photos/seed/icecream/400/300',
      category: 'Postres',
    },
    {
      id: 40,
      name: 'Churros con Chocolate',
      description: 'Churros calientes con salsa de chocolate.',
      longDescription: 'Crujientes por fuera, suaves por dentro. Churros recién hechos, espolvoreados con azúcar y canela, servidos con una taza de chocolate espeso para dipear.',
      price: 13000,
      imageUrl: 'https://picsum.photos/seed/churros/400/300',
      category: 'Postres',
    },
    {
      id: 41,
      name: 'Té Helado',
      description: 'Té negro endulzado con un toque de limón.',
      longDescription: 'Refrescante y clásico. Nuestro té helado se prepara fresco todos los días, endulzado a la perfección y con un toque de limón.',
      price: 6000,
      imageUrl: 'https://picsum.photos/seed/icetea/400/300',
      category: 'Bebidas',
    },
    {
      id: 42,
      name: 'Café Helado',
      description: 'Café frío con leche y toque de vainilla.',
      longDescription: 'Para los amantes del café que necesitan refrescarse. Café espresso frío mezclado con leche y un toque de sirope de vainilla, servido sobre hielo.',
      price: 8000,
      imageUrl: 'https://picsum.photos/seed/icedcoffee/400/300',
      category: 'Bebidas',
    },
    {
      id: 43,
      name: 'Cerveza Nacional',
      description: 'Elige tu cerveza local favorita.',
      longDescription: 'Acompaña tu comida con una cerveza nacional bien fría. Pregunta por las marcas disponibles.',
      price: 7000,
      imageUrl: 'https://picsum.photos/seed/beer/400/300',
      category: 'Bebidas',
    }
  ]);

  categories = computed(() => {
    const allCategories = this.products().map(p => p.category);
    return [...new Set(allCategories)];
  });

  getProducts() {
    return this.products.asReadonly();
  }

  deleteProduct(productId: number) {
    this.products.update(products => products.filter(p => p.id !== productId));
  }
}